### ISSUE TITLE
Resolution for Touchscreen on Pi

### ISSUE THREAD

**Issue by robert5974** [rsjudka/intelligent-auto#12]
Could the resolution be added for the Official Raspberry Pi touchscreen of 480x800?  We discussed this on Reddit already but I thought I'd create an issue to track the enhancement that resolves the issue of overlapping borders on the radio buttons/sliders in settings.

**Comment by rsjudka** [comment]
So I didn't end up making any "resolution" changes per se, since I want this app to be as dynamic as possible. I instead added the settings into scrollable views, so that additional settings can also be added in the future without worrying about size constraints.

Let me know if you still feel like things don't "fit" on your smaller screen, maybe we can also add scaling for things like buttons, text, etc.

**Comment by rsjudka** [comment]
you can find the changes in the `develop` branch

**Comment by robert5974** [comment]
I am building a clean Raspbian image right now and when it's done updating, I'll build out IA again.  Thanks.  I'll be back with results.

**Comment by robert5974** [comment]
So I built with the develop branch, and the scrolling menu works and looks great.  No overlapping at all. Great job!
