### ISSUE TITLE
Problems installing on RPi3B+

### ISSUE THREAD

**Issue by leobel96** [rsjudka/intelligent-auto#2]
I encountered many problems during installation:
1.  apt-get is unable to locate the dependency librtaudio5a. librtaudio6 installs without problems
2.  apt-get is unable to locate the dependency gstreamer1.0-qt5. I skipped its intallation. EDIT: maybe a solution [here](https://github.com/viktorgino/headunit-desktop/wiki/Building-QtGStreamer)
3.  Getting the following error when trying to build OpenAuto:
```
[  1%] Automatic MOC and UIC for target btservice
[  1%] Built target btservice_autogen
[  2%] Linking CXX executable /home/pi/Desktop/intelligent-auto/openauto/bin/btservice
/usr/bin/ld: cannot find -lpwd/../aasdk/lib/libaasdk_proto.so
/usr/bin/ld: cannot find -lpwd/../aasdk/lib/libaasdk_proto.so
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/btservice.dir/build.make:151: /home/pi/Desktop/intelligent-auto/openauto/bin/btservice] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/btservice.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```
It's the first time I try OpenAuto and I am starting from a clean installation of Raspbian Buster.

**Comment by rsjudka** [comment]
1) hmm i might be wrong but when i was building this on a RPi3 I needed to install librtaudio5a but maybe it could have been on an older version of Raspbian. I'll update the README but you should be fine with 6

2) gstreamer should only really be installed if you want to run this on a non-pi device (since it uses the Qt video library instead of the OMX library). I'll update the README but you should be fine without any of the gstreamer stuff

3) Looks like a problem with the cmake command... specifically the `pwd` (these should be backticks not single quotes). Could you try using the full path here instead(for example instead of -DAASDK_INCLUDE_DIRS="`pwd`/../aasdk/include" do -DAASDK_INCLUDE_DIRS="/home/pi/Desktop/intelligent-auto/aasdk/include")? Right now Im working on updating the build procedure so you only need to build once and wont need to worry about passing any paths. Should be done in a few hours.

**Comment by leobel96** [comment]
It would be fantastic if you write a simple bash script that installs everything paying attention to what device you are using (e.g. setting the correct flags for RPi) without having to update the README every time. Anyway I'll try the solution you suggested me for problem 3.

**Comment by leobel96** [comment]
@rsjudka Full paths solved the problem 3. I don't know why but copy-paste doesn't works for backtick: I tried many times but they get ignored.

**Comment by rsjudka** [comment]
@leobel96 I just pushed my changes to simplify the build process so no need to worry about those back ticks anymore :D

I'm going to hold off an creating any scripts yet just because I still feel like there may be some things that change along the way and I want to fully flesh out the entire process.

**Comment by rsjudka** [comment]
@leobel96 did you have any other issues with it? If not I'm going to close out this issue.

**Comment by leobel96** [comment]
The installation works fine now. I have had no time to test the program anyway. If I encounter other problems I open another issue.
