### ISSUE TITLE
[Enhancement] Control Buttons

### ISSUE THREAD

**Issue by robert5974** [rsjudka/intelligent-auto#37]
As requested, here are the items requested to change or update in the Control Buttons:
1. Add a pop-up menu for the power button.  Choose between Shutdown, Reboot, & Cancel

2. Add pop-up or notification acknowledging the actual saving of settings when the Save button is pressed

3. Possibly adding the selected theme color to the buttons when pressed ( just a thought)

**Comment by robert5974** [comment]
Should I edit this title to include "[Enhancement]" preceding?

**Comment by rsjudka** [comment]
went ahead and did it :slightly_smiling_face: 

need to start getting better organized with all this hah

**Comment by robert5974** [comment]
Ok.  Thanks.  I thought it was something you labeled afterwards lol.  I've never been this involved on GitHub.  I just remember the guy developing Crankshaft going back and marking what needed to be an enhancement and not only an issue.

**Comment by rsjudka** [comment]
power button pop up:
![Screenshot from 2020-06-14 17-43-46](https://user-images.githubusercontent.com/16892670/84605934-15461380-ae67-11ea-8095-bb25894179f2.png)

save notifier:
![Peek 2020-06-14 17-46](https://user-images.githubusercontent.com/16892670/84605943-242cc600-ae67-11ea-9cb9-dc086153339b.gif)

decided not to add the transparent backdrop for now because I'm not sure where transparency can currently be supported

because this relies on being to show the pop ups at the topmost layer, this wont get merged into develop until the openauto gstreamer stuff gets merged in (and made to be the only supported openatuo platform)

**Comment by robert5974** [comment]
Looks good!  Looking forward to it.
