### ISSUE TITLE
Show mouse cursor for debug purposes

### ISSUE THREAD

**Issue by leobel96** [rsjudka/intelligent-auto#5]
I haven't got a touch screen (I will buy one soon) so, the only way I have to interact with google Auto, is mouse but, with Android Auto open, cursor is hidden. Could you please add the possibility to show the mouse cursor for debug purposes?

**Comment by rsjudka** [comment]
this functionality kinda already exists (I just didn't publish it lol)

The app takes an optional width and height that you can use instead of having it be fullscreen. Since the intention of this was to be used for my personal debugging, I enabled the mouse too.

An example of running in this "debug" mode would be:
`./ia 1024 600`
